#!/bin/env python

import subprocess
import time

res = subprocess.run(['go', 'test', './...'], capture_output=True)
if res != 0:
  print(res.stdout.decode('utf-8'), flush=True)
  print(res.stderr.decode('utf-8'), flush=True)
  time.sleep(1) # Cheap hack to allow the output to flush
  res.check_returncode()
